### PR TITLE
David's exercise 3

### PR DESCRIPTION
**Pull request by lidavidm**
I feel like the CMake tests aren't testing what I intend them to, but atm I can't get to the documentation to figure it out.

(Also, building with `CXX=clang` instead of `CXX=clang++` was quite confusing.)

### CODE REVIEW

**Comment by ghost** [comment]
I also had trouble getting the env variables for the compiler to work at first, ha. Particularly that I didn't need to put in the version.
But how do you mean? I was using `CXX=clang++`, did only `CXX=clang` work for you?
Just tried using `CXX=clang` and looks like that doesn't work for me.

**Comment by lidavidm** [comment]
@genkimarshall I had `CXX=clang` because I was dumb, it didn't work:

```
~/Code/cornell/nskicpp-exercises/david/build-clang/ make
[100%] Building CXX object CMakeFiles/prompt_name.dir/prompt_name.cpp.o
Linking CXX executable prompt_name
CMakeFiles/prompt_name.dir/prompt_name.cpp.o: In function `main':
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x14): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x35): undefined reference to `std::cout'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x40): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x52): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x57): undefined reference to `std::cin'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x62): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x8c): undefined reference to `std::cout'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x97): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0xad): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0xdf): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0xf1): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0xfa): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x111): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x13a): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x15f): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/prompt_name.dir/prompt_name.cpp.o:/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text+0x168): more undefined references to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()' follow
CMakeFiles/prompt_name.dir/prompt_name.cpp.o: In function `__cxx_global_var_init':
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text.startup+0x13): undefined reference to `std::ios_base::Init::Init()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text.startup+0x19): undefined reference to `std::ios_base::Init::~Init()'
CMakeFiles/prompt_name.dir/prompt_name.cpp.o: In function `std::literals::string_literals::operator"" s(char const*, unsigned long)':
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text._ZNSt8literals15string_literalsli1sEPKcm[_ZNSt8literals15string_literalsli1sEPKcm]+0x33): undefined reference to `std::allocator<char>::allocator()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text._ZNSt8literals15string_literalsli1sEPKcm[_ZNSt8literals15string_literalsli1sEPKcm]+0x48): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&)'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text._ZNSt8literals15string_literalsli1sEPKcm[_ZNSt8literals15string_literalsli1sEPKcm]+0x56): undefined reference to `std::allocator<char>::~allocator()'
/home/lidavidm/Code/cornell/nskicpp-exercises/david/prompt_name.cpp:(.text._ZNSt8literals15string_literalsli1sEPKcm[_ZNSt8literals15string_literalsli1sEPKcm]+0x72): undefined reference to `std::allocator<char>::~allocator()'
CMakeFiles/prompt_name.dir/prompt_name.cpp.o:(.eh_frame+0x47): undefined reference to `__gxx_personality_v0'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/prompt_name.dir/build.make:85: recipe for target 'prompt_name' failed
make[2]: *** [prompt_name] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/prompt_name.dir/all' failed
make[1]: *** [CMakeFiles/prompt_name.dir/all] Error 2
Makefile:85: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ghost** [comment]
Haha, yeah, same output for me.

**Comment by pniedzielski** [comment]
I'll look at this in a little bit.

With regard to the build error, when you compile clang from source, it gives you a single executable that knows what to do correctly.  In Debian (and Arch, I guess?) there are two executables, probably because gcc makes them and it's good to be a drop-in replacement.  So `clang++` for your system, then?

I had very large instructions for building GCC and Clang yourself so we could all be sure we had the same development environment, but they were annoying and took forever to get right.  It's less trouble this way, surprisingly.  If you don't want to type the `CC=... CXX=...` part each time, you could make a `build-with-clang.sh` and `build-with-gcc.sh` that sets those for the duration of the shell.

**Comment by ghost** [comment]
Oh in yours you just have to use `clang`?
And yeah, might end up making that script, I've just been using bash history reverse search and it hasn't annoyed me enough. Yet. :P

**Comment by pniedzielski** [comment]
When I use the version that in Debian repositories, I have to use `clang++-3.7`.  But when I use a version I've compiled myself, it's just `clang-3.7`.

It's a good idea to use ones with version numbers if you can, because the ones without are the defaults for the distro, and may change.  We want to make sure we're using clang-3.6 or clang-3.7 and gcc-5 or gcc-5.1.

**Comment by lidavidm** [comment]
Fixed the header comment stuff.

**Comment by pniedzielski** [comment]
Alright, I think this is okay.  Clean up the commit history and I'll sign-off on all the commits and merge them in.

**Comment by lidavidm** [comment]
Please see https://github.com/nskicpp/exercises/pull/5

**Pull request closed without merging**
