### PR TITLE
[lesson3] Add solution to lesson 3 exercise

### PR DESCRIPTION
**Pull request by gharrma**
This solves the exercise involving greeting a user by name.
The solution compiles with g++-5 and clang++3.6.

Also, .gitkeep removed for being redundant, and .gitignore added
to ignore build files.

### CODE REVIEW

**Comment by gharrma** [comment]
**Re: CMake Testing**
Yeah, definitely forgot a backslash there. As for the mini program you give, it shows that we're not testing that the user's input is actually displayed after "Hello, "?

**Re: Corner Cases**
I know we could use `getline(...)` to get a full name. I think I understand the idea behind computational bases as well, but would you say that `getline(...)` makes up (or is part of) a computational basis? What about a function that reads from an input stream until it sees a particular character (that is supplied to the function as an argument)--would that be another basis? Not sure if that's what you're getting at here.

And yes, my program should probably check if the input string is empty in case there are sneaky users out there (or if an empty file gets piped in as input--who knows).

**Comment by pniedzielski** [comment]
1. Right, so our test isn't really testing what we want, and it also doesn't make clear the behavior it wants to test.  We can make programs that don't do what we want and pass the test, and it's pretty easy to do so.  Again, we don't know how to do that in CMake yet, but we'll see later a better way to do this.  @lidavidm 's solution to this was to manually pass in the input using shell features, which we can't rely on on multiple platforms, but barring that, it's a very good solution.
2. I think we're getting at it with that description.  Let's try to be a little more precise: `cin`'s `>>` with a `string` on its right-hand side isn't enough to form an _expressive_ basis on its own, because we have no way of reading everything until the end of a line.  It tokenizes the input stream (splits it into words based on whitespace), but discards what whitespace it reads.  We can't tell whether we've gotten to the end of a line.
   
   An example of a basis that allows us to read until the end of the line would be `>>` that returns consecutive nonspace characters and a `read_whitespace()` function that returns consecutive whitespace characters.  Then, we could alternate between `read_whitespace()` and `>>` until the whitespace string we get has a newline.  A little bit of string manipulation, and we have a line to return.
   
   But this distinction between whitespace and non-whitespace is a little bit arbitrary.  We're ending up with something like this:
   
   ```
     This \tisa string with\n a newline
   | |   |  |  ||     ||   |  |||      |
   ```
   
   Essentially, we're splitting at space/nonspace boundaries.  We could instead have a `tokenize()` function that returns all characters until the next space/nonspace boundary and use the same iteration trick to implement `getline()`.
   
   A third option for `cin` to provide would just be to implement `getline()`.  Then we could, well, get the rest of the line.  This could potentially be more efficient, because we don't have to search through each string for a newline; it's going to be doing that anyway, but the two interfaces we describe above throw that information away.
   
   We could expand this as you noted with a function `get_until_char()` which returns a string until we see the character we asked for.  We could even expand this to search for a regular expression.  `cin` actually has a `get_until_char()` function, but it's also spelled [`getline()`](http://en.cppreference.com/w/cpp/string/basic_string/getline)—don't worry about all the syntax in that link though.  You can write `getline(cin, str, 'a');` to read all characters until the first `a`.  So good design; the standard library also uses it. :smile:
   
   Finally, we could just have a `get_next_char()` and do all the parsing ourselves.  This (if we ignore error handling) is a maximally expressive computational basis for reading input from standard input, but it's hard to use and can be less efficient.

**Comment by pniedzielski** [comment]
Alright, I think this is good.  If you want to squash the commits, that's fine.  Otherwise, I'm ready to merge them in.  Is that okay?

**Comment by gharrma** [comment]
Yup, I'm ready to merge. Thanks Patrick!

**Comment by pniedzielski** [comment]
Forgot to merge.  Closing now.

**Pull request closed without merging**
