### PR TITLE
Add solutions to lesson 4 exercises

### PR DESCRIPTION
**Pull request by gharrma**
Update CMakeLists with test cases for each new exercise, along with new
compiler flags for runtime optimization and added safety checks.

Update test case for hello_person to use shell piping (thanks to David for
the idea).

All solutions compile cleanly with g++-5 and clang++-3.6

License: Boost

### CODE REVIEW

**Comment by pniedzielski** [comment]
Very good response.  See if you can rework the code to be clearer in the places I indicated.

Also, as per [this](https://nskicpp.slack.com/archives/general/p1435984591000002), you don't need to add `[lesson4]`; I thought it would make the history easier to read, but because the repo isn't broken into components with meaningful names, it makes it harder to read.

**Comment by gharrma** [comment]
Alright, I revised my solutions. Should be good to go.

**Comment by gharrma** [comment]
I think when I did a force push to my branch, it may have removed all of your comments :(
But thank you for the time you spent reviewing the code; the comments were helpful!

**Comment by gharrma** [comment]
Ok, fixed the `count += 1` vs. `++count` quirk.
(I originally did that because you said to avoid count++ for now, but I didn't realize you wanted ++count instead)
Ready to merge if you are :+1:

**Comment by gharrma** [comment]
Ok, squashed my original lesson 4 commit with the revision commit. Should be good to go?

**Comment by pniedzielski** [comment]
Looks good!  Merged with 43495e5af53c3c9e0712d770ee5529d80cf6dd5e.

**Pull request closed without merging**
