### PR TITLE
[lesson 3] Add `hello_name` solution

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pniedzielski** [comment]
Good job!  Compiles with no errors or warnings, and it looks like you understand the ideas I was trying to show.  Please respond to the things I said above, either by changing the code or answering the questions.

**Comment by ghost** [comment]
[Note for bookkeeping: in regards to the un-responded answers, internalized & followed-up elsewhere & in code].

**Comment by ghost** [comment]
Yeah I think it's ready to merge, thank you! :+1:

**Comment by pniedzielski** [comment]
Alright, merged.  Something I noticed: your commit messages don't have a blank second line.  To built-in tools, a message that looks like this:

```
Do something under 50 chars
This is a longer description.  Wraps at 72 chars.
```

is considered like this:

```
Do something under 50 chars This is a longer description. Wraps at 72 chars.
```

If you put a blank line between them, `shortlog` and `rebase -i` and so forth do what we want.  Just something to remember.  :)

I have to manually close this PR because GitHub PRs don't understand rebases and signing off.

**Comment by ghost** [comment]
Ah, well that explains why the second line in vim for git commit messages always was highlighted as an error. I didn't even think about how it's the same as error highlighting elsewhere until now, I never even thought to look up why for some reason. Also, GitHub nicely hid that away for me :P 
Well jeez, thanks for letting me know. That's a shame that all my commits now have that. Better late than never.

**Pull request closed without merging**
